### ISSUE TITLE
Use `app_hostname` when advertising grpc tracing endpoints

### ISSUE THREAD

**Issue by michaeldmitry** [canonical/tempo-operators#35]
### Bug Description

As part of the changes done in https://github.com/canonical/tempo-coordinator-k8s-operator/pull/163, we missed updating the grpc endpoints [here](https://github.com/canonical/tempo-coordinator-k8s-operator/blob/main/src/charm.py#L557).

```
receivers:
  - protocol:
      name: otlp_grpc
      type: grpc
    url: tempo-0.tempo-endpoints.jubilant-9b23ba63.svc.cluster.local:4317
  - protocol:
      name: otlp_http
      type: http
    url: https://tempo.jubilant-9b23ba63.svc.cluster.local:4318
```
grpc-based endpoints should also use the app hostname instead of the unit hostname

_Note_
Depending on the outcome of https://github.com/canonical/cos-coordinated-workers/pull/8, we can leverage the property/method that lives in the shared coordinator 

### To Reproduce

N/A

### Environment

N/A

### Relevant log output

```shell
N/A
```
